name: SFGPhotography
favicon: null
layout_spectrum: 0.5696761088911444
typography_spectrum: 0.21416970738209784
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4093239144422114
  lightness: 0.04473200812935829
  saturation: 0.47751965187489986
  rhythmicContrast: 0.4913672513794154
purpose: []
